/* ══════════════════════════════════════════════════════════════
   manifest.js — AUTO-GENERATED by generate.sh
   Do not edit manually. Run ./generate.sh to regenerate.
   ══════════════════════════════════════════════════════════════ */

const SLUGS = [
  "building-ascii-studio",
  "building-this-terminal"
];

const IMAGE_FILES = [
  { name: "terminal.txt", path: "images/terminal.txt" },
  { name: "xp-logo.txt", path: "images/xp-logo.txt" },
  { name: "ariana-ascii.txt", path: "assets/ariana-ascii.txt" },
  { name: "FURROW-CREDITS.txt", path: "assets/FURROW-CREDITS.txt" }
];

const SOURCE_TREE = {
  root: [
    { name: "index.html", path: "index.html", type: "html" },
    { name: ".nojekyll", path: ".nojekyll", type: "nojekyll" }
  ],
  js: [
    { name: "clock.js", path: "js/clock.js", type: "js" },
    { name: "cmatrix.js", path: "js/cmatrix.js", type: "js" },
    { name: "desktop.js", path: "js/desktop.js", type: "js" },
    { name: "earth.js", path: "js/earth.js", type: "js" },
    { name: "furrow.js", path: "js/furrow.js", type: "js" },
    { name: "shared.js", path: "js/shared.js", type: "js" },
    { name: "terminal.js", path: "js/terminal.js", type: "js" },
    { name: "widgets.js", path: "js/widgets.js", type: "js" }
  ],
  css: [
    { name: "clock.css", path: "css/clock.css", type: "css" },
    { name: "cmatrix.css", path: "css/cmatrix.css", type: "css" },
    { name: "desktop.css", path: "css/desktop.css", type: "css" },
    { name: "furrow.css", path: "css/furrow.css", type: "css" },
    { name: "mobile.css", path: "css/mobile.css", type: "css" },
    { name: "post.css", path: "css/post.css", type: "css" },
    { name: "terminal.css", path: "css/terminal.css", type: "css" }
  ],
  blog: [
    { name: "building-ascii-studio.md", path: "blog/building-ascii-studio.md", type: "md" },
    { name: "building-this-terminal.md", path: "blog/building-this-terminal.md", type: "md" }
  ],
  images: [
    { name: "ascii-studio-logo.svg", path: "images/ascii-studio-logo.svg", type: "svg" },
    { name: "terminal.txt", path: "images/terminal.txt", type: "txt" },
    { name: "xp-logo.txt", path: "images/xp-logo.txt", type: "txt" }
  ],
  assets: [
    { name: "ariana-ascii.txt", path: "assets/ariana-ascii.txt", type: "txt" },
    { name: "FURROW-CREDITS.txt", path: "assets/FURROW-CREDITS.txt", type: "txt" },
    { name: "RasterForgeRegular-JpBgm.ttf", path: "assets/RasterForgeRegular-JpBgm.ttf", type: "ttf" },
    { name: "windows-xp-logo.svg", path: "assets/windows-xp-logo.svg", type: "svg" },
    { name: "xp-sound.mp3", path: "assets/xp-sound.mp3", type: "mp3" }
  ],
  desktop: [
    { name: "index.html", path: "desktop/index.html", type: "html" }
  ],
};
