/* ════════════════════════════════════════════════════════════════
   shared.js  —  loaded by BOTH index.html and desktop.html
   Contains: frontmatter parser, date sort.
   Data (SLUGS, IMAGE_FILES, SOURCE_TREE) lives in manifest.js,
   which is auto-generated by ./generate.sh
   ════════════════════════════════════════════════════════════════ */

// ── Frontmatter parser ─────────────────────────────────────────────────────────
// Returns { meta: { slug, title, date, category, tags[], url, description, image },
//           body: string }
function parseFrontmatter(md) {
  const match = md.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  const meta = {};
  let body = md;
  if (match) {
    match[1].split("\n").forEach((line) => {
      const sep = line.indexOf(":");
      if (sep === -1) return;
      const k = line.slice(0, sep).trim();
      const v = line.slice(sep + 1).trim();
      meta[k] =
        k === "tags"
          ? v
              .split(",")
              .map((t) => t.trim())
              .filter(Boolean)
          : v;
    });
    body = md.slice(match[0].length).trim();
  }
  return { meta, body };
}

// ── Sort array of posts newest-first by .date string ─────────────────────────
function byDate(arr) {
  return [...arr].sort((a, b) =>
    b.date > a.date ? 1 : b.date < a.date ? -1 : 0,
  );
}
