#!/bin/bash
# ┌──────────────────────────────────────────────────────────┐
# │  generate.sh — scans the repo and writes js/manifest.js  │
# │  Runs automatically via git pre-commit hook.              │
# │  Manual: ./generate.sh                                    │
# └──────────────────────────────────────────────────────────┘
set -euo pipefail
cd "$(dirname "$0")"

OUT="js/manifest.js"

ext() { echo "${1##*.}"; }

{
cat << 'HEADER'
/* ══════════════════════════════════════════════════════════════
   manifest.js — AUTO-GENERATED by generate.sh
   Do not edit manually. Run ./generate.sh to regenerate.
   ══════════════════════════════════════════════════════════════ */
HEADER

# ── SLUGS ────────────────────────────────────────────────────
printf '\nconst SLUGS = [\n'
first=true
for f in blog/*.md; do
  [ -f "$f" ] || continue
  $first || printf ',\n'; first=false
  printf '  "%s"' "$(basename "$f" .md)"
done
printf '\n];\n'

# ── IMAGE_FILES ──────────────────────────────────────────────
printf '\nconst IMAGE_FILES = [\n'
first=true
for dir in images assets; do
  for f in "$dir"/*.txt; do
    [ -f "$f" ] || continue
    $first || printf ',\n'; first=false
    printf '  { name: "%s", path: "%s" }' "$(basename "$f")" "$f"
  done
done
printf '\n];\n'

# ── SOURCE_TREE ──────────────────────────────────────────────
printf '\nconst SOURCE_TREE = {\n'

# Root files
printf '  root: [\n'
first=true
for f in *.html .nojekyll; do
  [ -f "$f" ] || continue
  $first || printf ',\n'; first=false
  printf '    { name: "%s", path: "%s", type: "%s" }' "$(basename "$f")" "$f" "$(ext "$f")"
done
printf '\n  ],\n'

# Sub-directories
for dir in js css blog images assets; do
  [ -d "$dir" ] || continue
  printf '  %s: [\n' "$dir"
  first=true
  for f in "$dir"/*; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    [[ "$name" == .* ]] && continue
    [[ "$f" == "js/manifest.js" ]] && continue
    $first || printf ',\n'; first=false
    printf '    { name: "%s", path: "%s", type: "%s" }' "$name" "$f" "$(ext "$name")"
  done
  printf '\n  ],\n'
done

printf '};\n'
} > "$OUT"

echo "✓ Generated $OUT"
