#!/usr/bin/env node
// ─────────────────────────────────────────────
//  Build script: documentation/*.md → help-topics.js
//  Usage:  node studio/documentation/build.js
// ─────────────────────────────────────────────
var fs = require("fs");
var path = require("path");

var docDir = __dirname;
var outFile = path.join(docDir, "..", "help-topics.js");

// Read all .md files
var files = fs
  .readdirSync(docDir)
  .filter(function (f) {
    return f.endsWith(".md");
  })
  .sort();

var topics = {};

files.forEach(function (file) {
  var key = file.replace(".md", "");
  var md = fs.readFileSync(path.join(docDir, file), "utf8");
  topics[key] = markdownToHtml(md);
});

// Write output
var js = "// Auto-generated by documentation/build.js — do not edit directly\n";
js += "var helpTopics = {\n";
var keys = Object.keys(topics);
keys.forEach(function (key, i) {
  js += "  " + JSON.stringify(key) + ": " + JSON.stringify(topics[key]);
  if (i < keys.length - 1) js += ",";
  js += "\n";
});
js += "};\n";

fs.writeFileSync(outFile, js, "utf8");
console.log("Generated " + outFile + " (" + keys.length + " topics)");

// ─────────────────────────────────────────────
//  Minimal Markdown → HTML converter
//  Handles: ## h2, ### h3, - ul, 1. ol,
//           **bold**, *italic*, `code`,
//           paragraphs, raw HTML pass-through
// ─────────────────────────────────────────────
function markdownToHtml(md) {
  var lines = md.split("\n");
  var html = "";
  var inUl = false,
    inOl = false;
  var paraLines = [];

  function flushPara() {
    if (paraLines.length > 0) {
      html += "<p>" + inlineFormat(paraLines.join(" ")) + "</p>";
      paraLines = [];
    }
  }

  function closeList() {
    if (inUl) {
      html += "</ul>";
      inUl = false;
    }
    if (inOl) {
      html += "</ol>";
      inOl = false;
    }
  }

  for (var i = 0; i < lines.length; i++) {
    var trimmed = lines[i].trim();

    // Blank line — flush
    if (trimmed === "") {
      flushPara();
      closeList();
      continue;
    }

    // Headings
    if (trimmed.lastIndexOf("### ", 0) === 0) {
      flushPara();
      closeList();
      html += "<h3>" + inlineFormat(trimmed.slice(4)) + "</h3>";
      continue;
    }
    if (trimmed.lastIndexOf("## ", 0) === 0) {
      flushPara();
      closeList();
      html += "<h2>" + inlineFormat(trimmed.slice(3)) + "</h2>";
      continue;
    }

    // Unordered list
    if (trimmed.lastIndexOf("- ", 0) === 0) {
      flushPara();
      if (inOl) {
        html += "</ol>";
        inOl = false;
      }
      if (!inUl) {
        html += "<ul>";
        inUl = true;
      }
      html += "<li>" + inlineFormat(trimmed.slice(2)) + "</li>";
      continue;
    }

    // Ordered list
    if (/^\d+\.\s/.test(trimmed)) {
      flushPara();
      if (inUl) {
        html += "</ul>";
        inUl = false;
      }
      if (!inOl) {
        html += "<ol>";
        inOl = true;
      }
      html += "<li>" + inlineFormat(trimmed.replace(/^\d+\.\s/, "")) + "</li>";
      continue;
    }

    // Raw HTML pass-through
    if (trimmed.charAt(0) === "<") {
      flushPara();
      closeList();
      html += trimmed;
      continue;
    }

    // Regular text — accumulate into paragraph
    paraLines.push(trimmed);
  }

  flushPara();
  closeList();
  return html;
}

function inlineFormat(text) {
  // 1. Extract code spans first (protects *, ** inside code)
  var codes = [];
  text = text.replace(/`([^`]+?)`/g, function (m, p1) {
    codes.push("<code>" + p1 + "</code>");
    return "%%CODE" + (codes.length - 1) + "%%";
  });

  // 2. Bold: **text**
  text = text.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");

  // 3. Italic: *text*
  text = text.replace(/\*([^*]+?)\*/g, "<em>$1</em>");

  // 4. Restore code spans
  text = text.replace(/%%CODE(\d+)%%/g, function (m, idx) {
    return codes[parseInt(idx)];
  });

  return text;
}
